### ISSUE TITLE
Rails 5 not deleting tag with 0 tagging_count

### ISSUE THREAD

**Issue by FlyboyArt** [pat/gutentag#19]
Perhaps I'm missing something but when I have a model with 4 tags associated with it and then save the model with three tags. The fourth tag tagging_count goes to 0 but does not get deleted. 

user.tag_names = [ 'one', 'two', 'three', 'four' ]
user.save!

user.tag_names = [ 'one', 'two', 'three' ]
user.save!

tag 'four' is still in the Tag table but has a count of 0. My expecation is that when a Tag goes to zero it is automatically deleted. Wrong assumption???

Very nice implementation, I'm transitioning from acts_as_taggable_on as it's 210k and too complex for such a simple task as tagging. 

Thanks for the effort! - Art

**Comment by pat** [comment]
Hi Art

At this point in time, Gutentag doesn't delete unused tags - so yeah, wrong assumption :)

It would certainly be neat, and perhaps could be done as a single SQL query that removes any tags that don't have taggings? Pull requests are welcome if you want to give it a shot!

**Comment by pat** [comment]
Over a year later, and I've ended up pushing a helper class for this purpose. It's not called automatically - some people may wish for tags to remain present, even when unused? - but it's there for those who need it: `Gutentag::RemoveUnused.call`.

It's only present in the `master` branch at this point, but will be available in the next release (likely v2.1.0).
