### ISSUE TITLE
Using v0.7.0 doesn't include .tagged_with class method

### ISSUE THREAD

**Issue by turbogeek421** [pat/gutentag#20]
I've just installed the latest version of the gem (0.7.0) but it doesn't pull in any changes after commit ba9b446f5819d8efef4d107ea0ce7a8272d78586

**Comment by turbogeek421** [comment]
I have just forked this gem and increasing the Gem version, in my case I set it to 0.7.1, and it seems to fix the issue. I've added a pull request (#21), though I understand if the version number isn't right for you, or if there is more that needs to go into the next version.

**Comment by pat** [comment]
Ergh, about 14 months between releases. Sorry about that - just pushed 0.8.0 (took a little longer than I hoped, had to wrangle some things to ensure the test suite was happy with various Ruby and Rails versions.
