### ISSUE TITLE
Gutentag Article - Dead link to the tutorial

### ISSUE THREAD

**Issue by notapatch** [pat/gutentag#22]
Hi Pat,

Sorry, couldn't find a better way to contact you -  still, any day where you close an issue isn't a bad one ;-)

Your [Gutentag: Simple Rails Tagging](http://freelancing-gods.com/2013/07/11/gutentag-simple-rails-tagging.html) blog article has a dead link to '[the tutorial (dead)](http://railsconftutorials.com/2013/sessions/crafting_gems.html)' on how to craft the gem. Which is a shame as that was a big part of the article. Without a better idea I was going to suggest using the [waybackwhen link](https://web.archive.org/web/20151213065745/http://railsconftutorials.com/2013/sessions/crafting_gems.html).

Rich

**Comment by pat** [comment]
Thanks Rich, greatly appreciate you pointing this out :) Just pushed a fix to the blog post.
