### ISSUE TITLE
do not inject into AR

### ISSUE THREAD

**Issue by grosser** [pat/gutentag#30]
makes the setup a tiny bit more verbose but removed monkey-patching ...

```Ruby
class Foo < ActiveRecord::Base
  include Gutentag:: ActiveRecord
  has_many_tags
end
```

**Comment by pat** [comment]
I'm certainly not against this change - though I'd love to see it done with a deprecation warning somehow first. Granted, I'm not yet sure if/how that'd work!

**Comment by pat** [comment]
Closing this, as we've got the open PR #35 to deal with it.
