### ISSUE TITLE
Short tutorial

### ISSUE THREAD

**Issue by rgbskills** [pat/gutentag#48]
It would be nice to add a short rails tutorial in the readme, for example add tags red, green, blue to a products form :)

**Comment by pat** [comment]
Just added something to the wiki - let me know if any part of it doesn't make sense!
https://github.com/pat/gutentag/wiki/Examples

**Comment by elondaits** [comment]
The form example was quite useful. You should add it to the README or at least link it... the examples are not very easy to find otherwise.

**Comment by pat** [comment]
Thanks @elondaits - I've just added the link near the top of the README :)
