### ISSUE TITLE
Can't use tagged_with at STI Model

### ISSUE THREAD

**Issue by twbcs** [pat/gutentag#53]
ruby 2.5
rails 5.2
STI model
class Carrier < ApplicationRecord
  Gutentag::ActiveRecord.call self
end
class Author < Carrier
end

![fddc9640-a71b-460a-bdbf-2d52c8767673](https://user-images.githubusercontent.com/574479/38983772-bfb5f574-43f7-11e8-9b91-43d11a2dc225.png)

**Comment by pat** [comment]
Thanks for reporting this - I've just pushed a fix, which you can use now if you wish:

```ruby
# Waiting for 2.3.2 with the STI fix
gem "gutentag", "~> 2.3",
  :git    => "https://github.com/pat/gutentag.git",
  :branch => "master",
  :ref    => "d607880cb6"
```

I'll likely get a new gem release out next week.

**Comment by pat** [comment]
v2.3.2 has just been released with this fix.
