### ISSUE TITLE
Feature request: Add includable module or Rails concern

### ISSUE THREAD

**Issue by svkurowski** [pat/gutentag#62]
As a Quality of life improvement, it would look much nicer and feel more idiomatic if we could do
```ruby
include Gutentag::Taggable
```

instead of

```ruby
Gutentag::ActiveRecord.call self
```

If you agree, I can submit a PR that does this

**Comment by pat** [comment]
This has certainly been considered previously - see #30 and then #35. I'm happy enough to stick with the current approach, though the offer of a PR is certainly appreciated :)

**Comment by svkurowski** [comment]
My bad, I used https://github.com/pat/gutentag/issues?utf8=%E2%9C%93&q=is%3Aissue+concern+ to search for this and #30 is not in there because it doesn't contain the word `concern`, #35 is not in there because it's not an issue 😆

Feel free to close as wontfix although I'd certainly still appreciate an additional "convenience module" like this:

```ruby
module Taggable
  def Taggable.included(klass)
    Gutentag::ActiveRecord.call klass
  end
end
```

**Comment by pat** [comment]
I think I'll just close this without the convenience module - I'd rather avoid multiple ways of doing things, keeping the interface focused, though it is a neat suggestion.
