### ISSUE TITLE
Feature request: Support tag_names in ActiveRecord update and new

### ISSUE THREAD

**Issue by svkurowski** [pat/gutentag#63]
Right now, I'm doing:
```ruby
@mymodel = MyModel.new(params.require(:mymodel).permit(:mymodelattrib))
tag_names = params.require(:mymodel)[:tag_names]
@mymodel.tag_names = tag_names if tag_names.present?
```

it would be great if that could be reduced to

```ruby
@mymodel = MyModel.new(params.require(:mymodel).permit(:mymodelattrib, :tag_names))
```

And the same for ActiveRecord's `update` method.

**Comment by pat** [comment]
Ah, I'm surprised this doesn't work already - yes, keen to get this fixed. I'll look into it this week, but if you want to submit a PR, that's also welcome :)

**Comment by svkurowski** [comment]
I just checked again on the rails console and you're right - it is working. I must have made some mistake (probably passed in string instead of array of strings) and just assumed it wasn't working. Will re-open if I can reproduce.
