### ISSUE TITLE
ActiveModel::MissingAttributeError: missing attribute: tag_names

### ISSUE THREAD

**Issue by herohhnparaiso** [pat/gutentag#64]
After running through installation instructions, and including Gutentag on my model like so, I get an error whenever I call tag_names, which also results in me not being able to save any MyModel record due to the callbacks defined in the extension.

```
class MyModel < ActiveRecord::Base
  Gutentag::ActiveRecord.call self
end
```

```
c = MyModel.find id
c.tag_names
=> ActiveModel::MissingAttributeError: missing attribute: tag_names
from <...>/vendor/cache/ruby/2.3.0/gems/activerecord-5.0.0/lib/active_record/attribute_methods/read.rb:66:in `block in _read_attribute'
```

**Comment by pat** [comment]
From the stack trace, it looks like you're using Rails 5.0.0 - could you try upgrading to the latest 5.0.x release (5.0.7.2) and see if that helps?

**Comment by pat** [comment]
Closing this issue as it's been dormant for over a month. That said, if you've not found a solution, do feel free to continue the discussion here!
