### ISSUE TITLE
Any way to scope tags more granularly than at the Model level?

### ISSUE THREAD

**Issue by minter** [pat/gutentag#71]
I'm using Gutentag for a tagging feature in an application. The feature allows tagging of responses to a suggestion box.

Ideally, I'd like for the tag dropdown to only show tag names that have been used in a given box, as opposed to all tags used globally in the system. Looking at the docs, I'm not seeing a way to do that. Is there a way to use Gutentag to save/read tags scoped by a model ID?

**Comment by pat** [comment]
Hi @minter,

Just to clarify: are the tags currently attached to responses, and responses attached to suggestion boxes? If so, I don't believe there's an existing method/class that's going to do this query for you, but that doesn't mean it can't be done a touch more manually:

```ruby
# presuming SuggestionBox has many Responses.
box = SuggestionBox.first
response_ids = box.response_ids

tag_ids = Gutentag::Tagging.where(
  :taggable_type => 'Response',
  :taggable_id   => response_ids
).pluck(:tag_id).uniq

tags = Gutentag::Tag.where(:ids => tag_ids).pluck(:name)
```

This could be done in fewer queries if you want - you could use `Gutentag::Tag` as the initial relation and build out from there, selecting unique name values:

```ruby
box = SuggestionBox.first
response_ids = box.response_ids

Gutentag::Tag.joins(:taggings).where(
  :gutentag_taggings => {
    :taggable_id => response_ids,
    :taggable_type => 'Response'
  }
).distinct.pluck(:name)
```

Is this what you're after? Or have I misunderstood the request?

**Comment by minter** [comment]
@pat That's exactly what I needed - thank you! The use of `taggable_id` with the subset of responses for that box is where I was stuck.
