### ISSUE TITLE
ActiveRecord::Deadlocked and ActiveRecord::RecordNotUnique errors

### ISSUE THREAD

**Issue by ecielam** [pat/gutentag#74]
Use Case:  Straight forward parsing of content, adding tags to the Article model

Error:  Getting these errors:

ActiveRecord::Deadlocked: Mysql2::Error: Deadlock found when trying to get lock; try restarting transaction: UPDATE `gutentag_tags` SET `taggings_count` = COALESCE(`taggings_count`, 0) + 1 WHERE `gutentag_tags`.`id` = 6

ActiveRecord::RecordNotUnique: Mysql2::Error: Duplicate entry 'women' for key 'index_gutentag_tags_on_name': INSERT INTO `gutentag_tags` (`name`, `created_at`, `updated_at`) VALUES ('women', '2020-08-19 03:02:13', '2020-08-19 03:02:13')

I'm adding the tags via tag_names << 'tag' and then calling update or save on the article.

This only happens occasionally, and everything is running in Resque jobs.

**Comment by pat** [comment]
Hi there - thanks for reporting this.

I'll look into it all a bit further, but I just wanted to check: if the jobs fail initially, do they continue to fail, or is the issue usually resolved? (It sounds like it might be a concurrency/locking issue, but I just want to be sure)

**Comment by pat** [comment]
Closing this issue as there hasn't been any further details, and it's been several months - but if this problem's still happening, further comments are definitely welcome!

**Comment by sanifhimani** [comment]
Hello @pat, I've also seen quite a few `ActiveRecord::RecordNotUnique` errors lately in my project.
My use cases:

With Sidekiq:
* Sidekiq job calls a service that tags the user
* The user is tagged using: user << "tags" && user.save!

Controller:
* When the user opens an email
* The callback controller tags the user.

It doesn't fail again when the job or the callback retries.
