### ISSUE TITLE
ActiveRecord Query returning tag_names nil when there's tags

### ISSUE THREAD

**Issue by jmoon90** [pat/gutentag#78]
Gem Version: 2.5.4
Rails: 6.1.3
Ruby: 2.7.1

When I try AR query. 
```
Video.where.not(link: nil)
  => [#<Video:0x00007fe735627680
  id: "15d9dfa3-37d0-4d99-a3d8-35431a4d0da0",
...
  tag_names: nil>,
  ```
  When I call the object directly
  ```
[41] pry(#<VideoUploadsController>)> @video
=> #<Video:0x00007fe737b54b88
 id: "15d9dfa3-37d0-4d99-a3d8-35431a4d0da0",
...
tag_names: ["hips", "glutes"]>
 ```
 
 Using gutentag provided query
```
 Video.tagged_with(names: ['hips'])
 <ActiveRecord::Relation [#<Video id: "15d9dfa3-37d0-4d99-a3d8-35431a4d0da0", 
 ...
 tag_names: nil>]>
 ```
 
This came about when I trying `Video.where.not(tag_names: nil)`

 It returns values but tag_names is shown as nil. Not sure why

**Comment by pat** [comment]
The `tag_names` method is something a little different - it's not a column, but Gutentag _does_ allow Rails to track its dirty state (e.g. `video.tag_names_changed?`, etc). But making this work is a little messy (and differs between Rails versions).

All that said, are the results of calling `tag_names` on an object nil as well? Or is it just how they're displayed when inspected?

**Comment by jmoon90** [comment]
`All that said, are the results of calling tag_names on an object nil as well?` 
The tag_names are returned as I expect. It's simply the inspected version of it. Thought this might confuse others when they look at the object and see nil

**Comment by pat** [comment]
Yeah, it's a very fair point! I guess I wouldn't even expect it to be visible in the inspected output, given it's not a database column - and I don't think we'd want it loaded by default, as that's an extra database query.

Given how much of a hassle getting the dirty state tracking working properly has been, I'm going to leave the behaviour as it currently is. But should anybody be particularly bored, or feel super strongly about this - if you can find a way to hide the attribute from the inspected output, then I'd be open to a PR with that change :)
